# Data Preparation: Domain-Specific Train Data
## Version 1

## Setup

In [1]:
from pathlib import Path
import pandas as pd

In [2]:
ROOT = Path("..").resolve()

TRAIN_DIR = ROOT / "data" / "train" / "domain-specific"
LOG_DIR = TRAIN_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

CLEAN_TEXT = ROOT / "clean_text.py"

SYL_NORM = ROOT / "syl-normalizer" / "syl_normalizer.py"
SYL_DICT = ROOT / "syl-normalizer" / "final_syl_dictionary_13Feb2024.sorted.txt"

OPPA_WORD = ROOT / "oppaword" / "oppa_word.py"
OPPA_DICT = ROOT / "oppaword" / "myg2p_mypos.dict"

## Preprocess All Datasets: News Domain

### Remove Punctuations and Word Tags

In [3]:
!python {CLEAN_TEXT} -i {TRAIN_DIR}/train_news.raw -o {TRAIN_DIR}/train_news.cleaned.state1

Success! Cleaned text saved to: /home/lawun330/Desktop/burmese-domain-specific-lm/data/train/domain-specific/train_news.cleaned.state1

### Syllable Normalization

In [4]:
!python {SYL_NORM} \
    --dictionary {SYL_DICT} \
    --frequency 2 \
    --input {TRAIN_DIR}/train_news.cleaned.state1 \
    --output {TRAIN_DIR}/train_news.cleaned.state2 \
    --log {TRAIN_DIR}/logs/train_news.cleaned.state2.log \
    --error-output ../data/train/logs/train_news.cleaned.state2.errors \
    --fuzzy-distance 0

  Fuzzy correction: disabled

=== syl_normalizer summary (v0.6) ===
  Lines processed    :         11
  Tokens processed   :      1,594
  Passthrough        :         23
  Already valid      :         40

  Fixed - stage 1 (rules, token count)    :        5
  Fixed - stage 1 (individual rule apps)  :        5

  Fixed - stage 2 ngram (dup vowel)       :        0
  Fixed - stage 2 ngram (asat removal)    :        0
  Fixed - stage 2 ngram (char sub)        :        0
  Fixed - stage 2 ngram (medial order)    :        0
  Fixed - stage 2 ngram (dup+asat)        :        0

  Fixed - stage 2 dict (dup vowel)        :        0
  Fixed - stage 2 dict (asat removal)     :        0
  Fixed - stage 2 dict (char sub)         :        0
  Fixed - stage 2 dict (medial order)     :        0
  Fixed - stage 2 dict (dup+asat)         :        0

  Fixed - stage 3 (merge with previous)   :        0
  Fixed - stage 4 (compound split)        :      428

  Total fixed        :        433
  Still unknown      :      1,103
  Unknown rate       :    69.20%

### Word Segmentation (OppaWord)

In [5]:
!python {OPPA_WORD} \
  --input {TRAIN_DIR}/train_news.cleaned.state2 \
  --dict {OPPA_DICT} \
  --output {TRAIN_DIR}/train_news.cleaned.state3

## Preprocess All Datasets: Legal Domain

### Remove Punctuations and Word Tags

In [6]:
!python {CLEAN_TEXT} -i {TRAIN_DIR}/train_legal.raw -o {TRAIN_DIR}/train_legal.cleaned.state1

Success! Cleaned text saved to: /home/lawun330/Desktop/burmese-domain-specific-lm/data/train/domain-specific/train_legal.cleaned.state1

### Syllable Normalization

In [7]:
!python {SYL_NORM} \
    --dictionary {SYL_DICT} \
    --frequency 2 \
    --input {TRAIN_DIR}/train_legal.cleaned.state1 \
    --output {TRAIN_DIR}/train_legal.cleaned.state2 \
    --log {TRAIN_DIR}/logs/train_legal.cleaned.state2.log \
    --error-output ../data/train/logs/train_legal.cleaned.state2.errors \
    --fuzzy-distance 0

  Fuzzy correction: disabled

=== syl_normalizer summary (v0.6) ===
  Lines processed    :        194
  Tokens processed   :      1,163
  Passthrough        :         91
  Already valid      :         86

  Fixed - stage 1 (rules, token count)    :        0
  Fixed - stage 1 (individual rule apps)  :        0

  Fixed - stage 2 ngram (dup vowel)       :        0
  Fixed - stage 2 ngram (asat removal)    :        0
  Fixed - stage 2 ngram (char sub)        :        0
  Fixed - stage 2 ngram (medial order)    :        0
  Fixed - stage 2 ngram (dup+asat)        :        0

  Fixed - stage 2 dict (dup vowel)        :        0
  Fixed - stage 2 dict (asat removal)     :        0
  Fixed - stage 2 dict (char sub)         :        0
  Fixed - stage 2 dict (medial order)     :        0
  Fixed - stage 2 dict (dup+asat)         :        0

  Fixed - stage 3 (merge with previous)   :        0
  Fixed - stage 4 (compound split)        :      283

  Total fixed        :        283
  Still unknown      :        703
  Unknown rate       :    60.45%

### Word Segmentation (OppaWord)

In [8]:
!python {OPPA_WORD} \
  --input {TRAIN_DIR}/train_legal.cleaned.state2 \
  --dict {OPPA_DICT} \
  --output {TRAIN_DIR}/train_legal.cleaned.state3

## Preprocess All Datasets: Religion Domain

### Remove Punctuations and Word Tags

In [9]:
!python {CLEAN_TEXT} -i {TRAIN_DIR}/train_religion.raw -o {TRAIN_DIR}/train_religion.cleaned.state1

Success! Cleaned text saved to: /home/lawun330/Desktop/burmese-domain-specific-lm/data/train/domain-specific/train_religion.cleaned.state1

### Syllable Normalization

In [10]:
!python {SYL_NORM} \
    --dictionary {SYL_DICT} \
    --frequency 2 \
    --input {TRAIN_DIR}/train_religion.cleaned.state1 \
    --output {TRAIN_DIR}/train_religion.cleaned.state2 \
    --log {TRAIN_DIR}/logs/train_religion.cleaned.state2.log \
    --error-output ../data/train/logs/train_religion.cleaned.state2.errors \
    --fuzzy-distance 0

  Fuzzy correction: disabled

=== syl_normalizer summary (v0.6) ===
  Lines processed    :        243
  Tokens processed   :        683
  Passthrough        :         22
  Already valid      :         14

  Fixed - stage 1 (rules, token count)    :        2
  Fixed - stage 1 (individual rule apps)  :        2

  Fixed - stage 2 ngram (dup vowel)       :        0
  Fixed - stage 2 ngram (asat removal)    :        0
  Fixed - stage 2 ngram (char sub)        :        0
  Fixed - stage 2 ngram (medial order)    :        0
  Fixed - stage 2 ngram (dup+asat)        :        0

  Fixed - stage 2 dict (dup vowel)        :        0
  Fixed - stage 2 dict (asat removal)     :        0
  Fixed - stage 2 dict (char sub)         :        0
  Fixed - stage 2 dict (medial order)     :        0
  Fixed - stage 2 dict (dup+asat)         :        0

  Fixed - stage 3 (merge with previous)   :        0
  Fixed - stage 4 (compound split)        :      239

  Total fixed        :        241
  Still unknown      :        408
  Unknown rate       :    59.74%

### Word Segmentation (OppaWord)

In [11]:
!python {OPPA_WORD} \
  --input {TRAIN_DIR}/train_religion.cleaned.state2 \
  --dict {OPPA_DICT} \
  --output {TRAIN_DIR}/train_religion.cleaned.state3

## Load All Datasets

In [12]:
df_news_cleaned = pd.read_csv(f"{TRAIN_DIR}/train_news.cleaned.state3", header=None, names=["text"])
df_news_cleaned

                                                 text
0   ရုရှား ဖက် ဒ ရေး ရှင်း နိုင် ငံ ရဲ့ ကာ ကွယ် ရေ...
1   တိ ဘက် ဘုန်း တော် ကြီး ဒ လိုင် လား မား ကို ဂရမ...
2   ခ ရစ္စ မတ် ကာ လ ရောက် ဖို့ အ ဝေး ကြီး လို နေ သ...
3   အ မေ ရိ ကန် က အီ ရန် ကို ပြင်း ထန် တဲ့ တိုက် ခ...
4   နှစ် စဉ် ဒီ လို အ ချိန် တွေ ကို ရောက် လာ ပြီ ဆ...
5   ဗင် နီ ဇွဲ လား အ မျိုး သား လွှတ် တော် မှာ ရေ န...
6   အ မေ ရိ ကန် လေ ယာဉ် တင် သင်္ဘော အုပ် စု ယူ အက်...
7   Scrabble လို့ ခေါ် တဲ့ စာ လုံး တွေ ကို ဆက် တဲ့...
8   ရှမ်း မြောက် နယ် မြောက် ပိုင်း ကိုး က န့် ဒေသ ...
9   တရုတ် နိုင် ငံ ကို ရောက် ရှိ နေ တဲ့ ဗြိ တိ သျှ...
10  တရုတ် ပြည် သူ့ လွတ် မြောက် ရေး တပ် မ တော် ရဲ့ ...

In [13]:
df_legal_cleaned = pd.read_csv(f"{TRAIN_DIR}/train_legal.cleaned.state3", header=None, names=["text"])
df_legal_cleaned

                                                  text
0            ပြည် ထောင် စု သမ္မတ မြန် မာ နိုင် ငံ တော်
1    အ မျိုး သား ကာ ကွယ် ရေး နှင့် လုံ ခြုံ ရေး ကော...
2         မြန် မာ နိုင် ငံ ကူး လက် မှတ် ဆိုင် ရာဥ ပ ဒေ
3    အ မျိုး သား ကာ ကွယ် ရေး နှင့် လုံ ခြုံ ရေး ကော...
4           ၁၃၈၇ ခု နှစ် တ ပေါင်း လ ပြည့် ကျော် ၁၅ ရက်
..                                                 ...
144  ခ မြန် မာ နိုင် ငံ ကူး လက် မှတ် ထုတ် ပေး သ ည့်...
145                                    ၃၇ မည် သူ မ ဆို
146  က သက်တမ်း ရှိ နေ သော သာ မန် နိုင် ငံ ကူး လက် မ...
147  ခ ပယ် ဖျက် ထား သ ည့် မြန် မာ နိုင် ငံ ကူး လက် ...
148  ၃၈ မည် သူ မျှ ဤဥ ပ ဒေ ပါ ပြဋ္ဌာန်း ချက် တစ် ရပ...

[149 rows x 1 columns]

In [14]:
df_religion_cleaned = pd.read_csv(f"{TRAIN_DIR}/train_religion.cleaned.state3", header=None, names=["text"])
df_religion_cleaned

                                                  text
0                           ရှု ပွား ဆင် ခြင် သော အ ခါ
1    တရား ရှု မှတ် သော အ ခါ အ ရှု ခံ ဟူ၍ လည်း ကောင်...
2       လည်း ကောင်း နှစ် မျိုး ရှိ သည် ကို သိ ထား အပ်၏
3                             အ ရိုး စု သ တိ ဉာဏ် ပ ညာ
4                 ၃၂ ပါး ကောဋ္ဌာ သ အ စု သ တိ ဉာဏ် ပ ညာ
..                                                 ...
208  အ ခြင်း အ ရာ အား ဖြ င့် တည် ၏ ထို သို့ တည် သူ ...
209  ဖောက် ပြန် ၏ တစ် မျိုး တစ် ဖုံ ဖြစ်၏ ထို သူ အာ...
210  တစ် မျိုး တစ် ဖုံ ဖြစ် ခြင်း ကြော င့် စိုး ရိမ...
211        ပြင်း စွာ ပင် ပန်း မှု တို့ သည် ဖြစ် ကုန် ၏
212                     ခန္ဓ သံ ယုတ် န ကု လ ပီ တု သုတ်

[213 rows x 1 columns]

## All Final Datasets: Exploring File Size

In [15]:
!ls -lh {TRAIN_DIR}/train_news.raw {TRAIN_DIR}/train_news.cleaned.state3

-rw-rw-r-- 1 lawun330 lawun330 77K May 16 08:11 /home/lawun330/Desktop/burmese-domain-specific-lm/data/train/domain-specific/train_news.cleaned.state3
-rw-rw-r-- 1 lawun330 lawun330 72K May 16 07:16 /home/lawun330/Desktop/burmese-domain-specific-lm/data/train/domain-specific/train_news.raw

In [16]:
!ls -lh {TRAIN_DIR}/train_legal.raw {TRAIN_DIR}/train_legal.cleaned.state3

-rw-rw-r-- 1 lawun330 lawun330 59K May 16 08:11 /home/lawun330/Desktop/burmese-domain-specific-lm/data/train/domain-specific/train_legal.cleaned.state3
-rw-rw-r-- 1 lawun330 lawun330 55K May 16 07:09 /home/lawun330/Desktop/burmese-domain-specific-lm/data/train/domain-specific/train_legal.raw

In [17]:
!ls -lh {TRAIN_DIR}/train_religion.raw {TRAIN_DIR}/train_religion.cleaned.state3

-rw-rw-r-- 1 lawun330 lawun330 29K May 16 08:11 /home/lawun330/Desktop/burmese-domain-specific-lm/data/train/domain-specific/train_religion.cleaned.state3
-rw-rw-r-- 1 lawun330 lawun330 28K May 16 07:54 /home/lawun330/Desktop/burmese-domain-specific-lm/data/train/domain-specific/train_religion.raw

## References
- ```bibtex
  @misc{syl_normalizer,
    author       = {Ye Kyaw Thu},
    title        = {{Syllable Normalization Tool for Myanmar Language}},
    version      = {0.6},
    month        = {May},
    year         = {2026},
    publisher    = {GitHub},
    url          = {https://github.com/ye-kyaw-thu/syl-Normalizer/tree/main/ver_0.6},
    note         = {Accessed: YYYY-MM-DD},
    institution  = {Language Understanding Lab (LU Lab), Myanmar}
  }
  ```

- ```bibtex
  @misc{oppaWord_2025,
    author       = {Ye Kyaw Thu},
    title        = {{oppaWord: Hybrid DAG+Bi-MM+LM Myanmar Word Segmenter}},
    version      = {1.0},
    month        = {August},
    year         = {2025},
    publisher    = {GitHub},
    url          = {https://github.com/ye-kyaw-thu/oppaWord},
    note         = {Accessed: YYYY-MM-DD},
    institution  = {Language Understanding Lab (LU Lab), Myanmar}
  }
  ```